### ISSUE TITLE
Support simultaneous control of multiple power supplies 

### ISSUE THREAD

**Issue by jkelley** [jkelley/power-control#4]

**Comment by jkelley** [comment]
Consider a hierarchical config scheme like YAML, e.g.
```
group1:
  type: Kepco
  port: 5025
  supply1:
    hostname: drts-pwr1p
  supply2:
    hostname: drts-pwr1n
    port: 5026

group2:
  type: Keysight
  supply1:
    hostname: drts-pwr3
```
